#!/bin/bash
set -e

/etc/rc3.d/S01mysql start

# wait for server to start
for i in {30..0}; do
			if echo 'SELECT 1' | mysql &> /dev/null; then
				break
			fi
			echo 'MySQL init process in progress...'
			sleep 1
		done

echo "CREATE DATABASE IF NOT EXISTS drupal ;" | mysql
echo "CREATE USER IF NOT EXISTS 'drupal'@'localhost' IDENTIFIED BY 'drupal' ;" | mysql
echo "GRANT ALL ON \`drupal\`.* TO 'drupal'@'localhost' ;" | mysql

/usr/local/bin/apache2-foreground